### PR TITLE
fix: do not override user-provided options

### LINKED ISSUE #460: Compute module constructor adds apiEndpoint attribute to the given configuration
I've been using version 0.8.0 of @google-cloud/compute for a long time. A couple of months ago I've decided to move to what was the latest at the moment: version 1.2.0.
I'm using also @google-cloud/storage and I've updated that as well (from 1.5.0 to 4.7.0).

My app started to have random problems getting a 404 when I tryied to access private resources. After restarting my app it was working for some time then, after running smoothly for days, it was having problems.

I 've identified the problem in this call:

```
var gce = new (require("@google-cloud/compute"))(MyConf);
```

This call changes the given configuration by adding a new attribute:
`{ apiEndpoint: 'compute.googleapis.com' }`

The MyConf object is created as at the beginning of my app and it's used for both calls: compute and storage. 
The compute call adds the attribute that gives problem when I use that same configuration as parameter for the storage module.

- OS: Linux alpine inside Docker
- Node.js version: 12.18.0
- npm version: 6.14.4
- `@google-cloud/compute` version: 1.2.0

I've solved my problem by cloning the MyConf object before calling the compute module's contructor but I think that it would be better if the compute library did't change the configuration as the storage module does.

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #460

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -82,7 +83,13 @@ const Image = require('./image.js');
  */
 class Compute extends common.Service {
   constructor(options = {}) {
-    options.apiEndpoint = options.apiEndpoint || 'compute.googleapis.com';
```
Comment (JustinBeckwith) [inline src/index.js:85]: Oh bother ...  guessing this isn't the only place I did that 😬   @stephenplusplus could I trouble you to do a broad search for this pattern in our libs (I use `@google/repo` to do this) and see where else I biffed it?

**Review by JustinBeckwith — APPROVED** [review]
